### PR TITLE
Add Loongarch64 support

### PR DESCRIPTION
**Pull request by zhaixiaojuan**
Loongarch is a new RISC architecture.
Loongarch doc: https://github.com/loongson-community/LoongArch-Documentation/

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Is there an upstream rust target specification for this target?

**Comment by zhaixiaojuan** [comment]
Yes, the definition of this target is based on the rust target specification.
And regarding rust's support for loongarch64 architecture, we are under development.

**Comment by alexcrichton** [comment]
Hm I don't see the target here? https://github.com/rust-lang/rust/tree/master/compiler/rustc_target/src/spec

**Comment by zhaixiaojuan** [comment]
Sorry, we are still  testing  and  developing rust-lang/rust locally. After the testing is completed, we will submit it to the upstream community.

**Comment by alexcrichton** [comment]
Ah ok sounds good, would you be ok if I hold off on merging this until your target is closer to being merged into rust-lang/rust?

**Comment by zhaixiaojuan** [comment]
Of course. 
However, the integration of rust-lang/rust and its dependent library libc into the community may be a long-term work, and it will take a while.

**Comment by zhaixiaojuan** [comment]
If cc-rs can be incorporated into the community, it will be friendly to users of the new architecture, because they do not need to manually adapt it locally every time they use it.

**Comment by alexcrichton** [comment]
Yes that makes sense @zhaixiaojuan, but I prefer to have targets landed in rust-lang/rust before they're added here.

**Comment by heiher** [comment]
@alexcrichton The [loongarch64-unknown-linux-gnu](https://github.com/rust-lang/rust/pull/96971) was added as a tier 3 target, could you review this patch again please?

**Review by JohnTitor — APPROVED** [review]
Thank you!

**Pull request merged**
