### PR TITLE
Release cc v1.0.84

### LINKED ISSUE #893: Cut 1.0.84 Release
Cutting 1.0.84 would help us to solve issues with compiling on target iOS platforms.

We recently run into an issue with https://github.com/rust-lang/libz-sys crate where it would not be able to correctly compile a simple `.c` file on target iOS platform due to bitcode being enabled for all of iOS / watch OS builds. 

Bitcode was disabled as part of https://github.com/rust-lang/cc-rs/pull/812 but it's not included in 1.0.83 version of `cc` crate.

### PR DESCRIPTION
**Pull request by NobodyXu**
Resolve #893

### CODE REVIEW

**Comment by NobodyXu** [comment]
I opened this PR so that @thomcc you can merge and cut a new release at anytime you want

**Comment by thomcc** [comment]
I'll do this tomorrow morning.

**Comment by NobodyXu** [comment]
Good, I will leave this PR open so that you can approve and merge it tomorrow.

**Review by thomcc — APPROVED** [review]

**Comment by thomcc** [comment]
Published. Will get relnotes up soonish.

**Pull request merged**
