### PR TITLE
Prioritize RUSTC_LINKER over target->cross-compile-prefix table.

### PR DESCRIPTION
**Pull request by dot-asm**
Rationale is that if rustc is explicitly instructed to use a specific linker, using it as base for cross-compile prefix would be better aligned with user expectations.

This is in response to #766. Should fix #654.

### CODE REVIEW

**Comment by dot-asm** [comment]
Re-based and aligned with recent MSRV adjustment.

**Review by thomcc — APPROVED** [review]
Hmm, sorry, I think I missed this PR when it was submitted. It seems hard to argue with this, thanks.

**Comment by thomcc** [comment]
I'm going to let it sit shortly since I'd like to test it a little, but will merge it later this week.

**Comment by thomcc** [comment]
Eh, I'll just test it on master when I get to it.

**Comment by dot-asm** [comment]
You should be able to close #766 and even #637 (since earlier actually).

**Pull request merged**
