### PR TITLE
Add visionOS support

### PR DESCRIPTION
**Pull request by madsmtm**
I haven't added this to CI, as the Rust builds themselves are still somewhat broken until https://github.com/rust-lang/libc/pull/3568 lands.

CC @BlackHoleFox

### CODE REVIEW

**Comment by QuentinPerez** [comment]
We were definitely working on the same thing; I made almost the same changes. The only differences are the XROS_DEPLOYMENT_TARGET and this additional check on lines 2658 and 2674
```rust
                // there is no -m{}os-version-min for watchos, tvos, visionos
                if matches!(os, AppleOs::Ios | AppleOs::MacOs) {
                    cmd.args.push(
                        format!("-m{}os-version-min={}", sdk_details.sdk_prefix, min_version)
                            .into(),
                    );
                }

```

**Comment by madsmtm** [comment]
> there is no -m{}os-version-min for watchos, tvos, visionos

There is, see [Clang's docs for the `availability` attribute](https://clang.llvm.org/docs/AttributeReference.html#availability) and [Clang's docs for the flag itself](https://clang.llvm.org/docs/ClangCommandLineReference.html#cmdoption-clang-mtvos-version-min).

However, you right that it does not exist for visionOS, I've opened https://github.com/llvm/llvm-project/issues/88271 for that.

**Comment by madsmtm** [comment]
Using just `--target` is [recommended by Clang Driver developers](https://github.com/llvm/llvm-project/issues/88271#issuecomment-2050425068), which we already do, so I think that is a non-issue.

Have opened https://github.com/rust-lang/cc-rs/issues/1030 to track removing the other flags from Apple targets.

**Review by BlackHoleFox — APPROVED** [review]
Nice :D

**Comment by NobodyXu** [comment]
Thank you!

**Pull request merged**
