### PR TITLE
Continue to support binutils ar

### PR DESCRIPTION
**Pull request by jonhoo**
sfackler [observed] that the `binutils` package [provides] binaries named `$target-ar` (with no `-gcc`). This patch augments the change made in #735 to continue picking those up too.

[observed]: https://github.com/alexcrichton/openssl-src-rs/pull/163#issuecomment-1292439189
[provides]: https://packages.debian.org/bullseye/amd64/binutils-aarch64-linux-gnu/filelist

### CODE REVIEW

**Comment by jonhoo** [comment]
cc @sfackler

**Comment by sfackler** [comment]
What is the rationale for this change? I think it's generally expected you have a cross binutils in addition to a cross gcc if you are cross compiling. Binutils is a dependency of gcc in Ubuntu for example.

**Comment by jonhoo** [comment]
I came across this when I was in an environment where only `${target}-gcc-ar` was on `$PATH`, and not the tools provided by binutils. Whether that's a _common_ situation is hard for me to say, but it does seem like it should be a supported one given that it's a standard part of the GCC distributions.

**Review by thomcc — APPROVED** [review]

**Comment by thomcc** [comment]
This should be pretty harmless, and avoid anything bad that would be caused by #735. I have seen the `blah-gcc-ar` before, so I'll merge it.

**Pull request merged**
