### PR TITLE
Change ucrt and windows10sdk detection to match vcvars.

### PR DESCRIPTION
**Pull request by jrmuizel**
I had an installation of the 10.0.17763 sdk that did had files
in Lib/10.0.17763.0 but not in Include/10.0.17763.0. vcvars handled
this correctly but cc-rs did not.

### CODE REVIEW

**Comment by jrmuizel** [comment]
I'm not sure why my installation lacked Include files. Reinstalling it fixed the problem so maybe it's not worth taking this, but I figured it would be good to at least put it out there.

**Comment by alexcrichton** [comment]
This is unfortunately pretty finnicky code, and it's also basically untesable in the sense that I've got no idea if this regresses environments which work today. (although it does look like VS2019 regressed on CI?)

If this ended up being fixable on your end though maybe it's best then to not take it just yet?

**Comment by nico-abram** [comment]
@jrmuizel Were you able to figure out why you were missing the directory in your installation? I wonder if there is some optional component in the VS installer for the .libs . Then again, if you didn't have the .libs I don't think things would link correctly even if cc-rs found the folders.
Also, is it possible your comment in the original message is backwards w.r.t "Lib" and "Include"? (Looking at the code change it looks like you fixed it by making cc-rs look for include instead of dir, so I assume you had include and you didn't have lib)

> and it's also basically untesable in the sense that I've got no idea if this regresses environments which work today.

 @alexcrichton If this is actually a problem I wonder if we could keep the detection via /lib but fall back to /include if that fails?
 I'm thinking something like this
 ```rs
        let max_libdir = |sub: &'static str| -> Option<(PathBuf, String)> {
	          let readdir = Path::new(&root).join(sub).read_dir().ok()?;
	          let max_libdir = readdir
	              .filter_map(|dir| dir.ok())
	              .map(|dir| dir.path())
	              .filter(|dir| {
	                  dir.components()
	                      .last()
	                      .and_then(|c| c.as_os_str().to_str())
	                      .map(|c| c.starts_with("10.") && dir.join("ucrt").is_dir())
	                      .unwrap_or(false)
	              })
	              .max()?;
        };
        let max_libdir = max_libdir("lib").unwrap_or_else(|| max_libdir("include"));
```

**Comment by jrmuizel** [comment]
I wasn't able to figure out why I was missing the directory. I believe my original comment is correct, by checking for include files instead of lib files `cc-rs` skips the candidate sdk that's missing the include files. From what I recall, this matches what vcvars checks.

**Comment by nico-abram** [comment]
Ohh, I understand now. So you had multiple SDKs and you wanted the skip the one without the include files. That explains why you didn't get linker errors, since that second SDK presumably had both the lib and include folders. Checking both "lib" and "include" as I proposed above would then not fix this, since it would still find the one without the include folder first.

Although maybe what we could do is look for "include" first, and when we find one we *also* find the lib folder with the same mechanism as now for that same SDK version. If we find no "include" folder or we find one without a lib folder, we fall back to searching for just "lib". I think that should prioritize SDKs with an include folder over ones without one, but it should still work for some obscure case where someone is currently compiling with an SDK without include files correctly.

The current `get_ucrt_dir` looks this

```rs
    fn get_ucrt_dir() -> Option<(PathBuf, String)> {
        let key = r"SOFTWARE\Microsoft\Windows Kits\Installed Roots";
        let key = LOCAL_MACHINE.open(key.as_ref()).ok()?;
        let root = key.query_str("KitsRoot10").ok()?;
        let readdir = Path::new(&root).join("lib").read_dir().ok()?;
        let max_libdir = readdir
            .filter_map(|dir| dir.ok())
            .map(|dir| dir.path())
            .filter(|dir| {
                dir.components()
                    .last()
                    .and_then(|c| c.as_os_str().to_str())
                    .map(|c| c.starts_with("10.") && dir.join("ucrt").is_dir())
                    .unwrap_or(false)
            })
            .max()?;
        let version = max_libdir.components().last().unwrap();
        let version = version.as_os_str().to_str().unwrap().to_string();
        Some((root.into(), version))
    }

```

With the method I'm proposing it could look like this. I'm not sure if this is too much complexity or can be simplified.
```rs
    fn get_ucrt_dir() -> Option<(PathBuf, String)> {
        let key = r"SOFTWARE\Microsoft\Windows Kits\Installed Roots";
        let key = LOCAL_MACHINE.open(key.as_ref()).ok()?;
        let root = key.query_str("KitsRoot10").ok()?;

        let read_incdir = Path::new(&root).join("include").read_dir().ok()?;
        let read_libdir = Path::new(&root).join("lib").read_dir().ok()?;
        // vcvars finds the SDK using the include dir. cc-rs used to look for the lib dir
        // What we do now is look for include dirs, but also make sure that SDK has a library directory
        // If that fails, we fall back to the previous cc-rs behaviour and find the SDK using the lib folder
        let filter_libdir = |dir: &PathBuf| {
            dir.components()
                .last()
                .and_then(|c| c.as_os_str().to_str())
                .map(|c| c.starts_with("10.") && dir.join("ucrt").is_dir())
                .unwrap_or(false)
        };
        let max_incdir = read_incdir
            .filter_map(|dir| dir.ok())
            .map(|dir| dir.path())
            .filter(|dir| {
                dir.components()
                    .last()
                    .and_then(|c| c.as_os_str().to_str())
                    .map(|c| {
                        c.starts_with("10.")
                            && dir.join("ucrt").is_dir()
                            && filter_libdir(&Path::new(&root).join("lib").join(c))
                    })
                    .unwrap_or(false)
            })
            .max();
        let max_libdir = read_libdir
            .filter_map(|dir| dir.ok())
            .map(|dir| dir.path())
            .filter(|dir| filter_libdir(dir))
            .max();

        let sdk_dir = max_incdir.or(max_libdir)?;
        let version = sdk_dir.components().last().unwrap();
        let version = version.as_os_str().to_str().unwrap().to_string();
        Some((root.into(), version))
    }
```

**Comment by ChrisDenton** [comment]
As Alex said, this sort of thing isn't really tested atm so I do think we need a fallback because we don't want to break backwards compatibility (maybe someone only needs the libs). And I would want to try testing locally with a no-includes install (presumably the installer has options not to include the includes?). But otherwise I'm happy for us to check for includes.

Would you be interested in rebasing and adding a fallback as suggested? Or maybe @nico-abram would be willing to submit a PR? Sorry this has been open so long; there are more maintainers now and we're slowly working to reduce the backlog.

**Comment by ChrisDenton** [comment]
Ok, I'm going to close this as inactive but if anyone wants to continue working on this then feel very free to do so.

**Pull request closed without merging**
