### PR TITLE
Bump MSRV to 1.53.0 and re-enable macos MSRV check

### PR DESCRIPTION
**Pull request by NobodyXu**
To solve the issue mentioned https://github.com/rust-lang/cc-rs/pull/889#issuecomment-1788887737

### CODE REVIEW

**Review by thomcc — APPROVED** [review]
Looks great, thanks.

**Comment by NobodyXu** [comment]
Oops, it looks like 1.53 still has problem with linking on latest macos.
Will revert that change.

**Comment by thomcc** [comment]
Hm, do you know which version fixes it?

**Comment by NobodyXu** [comment]
> Hm, do you know which version fixes it?

Probably 1.56 or 1.58, had the same issue in https://github.com/cargo-bins/jobslot , however even 1.56 might be too new for some users (@dot-asm ).

Given that there's only one line of `cfg!(target_os = "macos")` which does not conditionally pull in new code but instead evalutes to a boolean, I think it's fine not checking on macos.

**Pull request merged**
