### PR TITLE
add as_excutable option

### PR DESCRIPTION
**Pull request by ds1sqe**
add new option on build
( as_executable(flag:bool) )
which create executable output and 
do not compile as lib

### CODE REVIEW

**Review by NobodyXu — CHANGES_REQUESTED** [review]
Hello, thanks for the PR, but I am hesitant to merge it.

cc is designed for compiling to static archive instead of executable, it would be a lot more work in supporting executable.

**Comment by ds1sqe** [comment]
But it's will be great if can compile into executable, and i think we can do that by a little efforts.
So why do not add feature with unstable feature?
and with my PR, we can compile as executable (if the "files" have unique main) on gcc and clang and msvc, if the language is C or C++.
with existing "out_dir" and compile(`path`) option.

**Comment by ds1sqe** [comment]
And also there are some projects which have to compile some c / cpp project and configure root rust project with compiled c / cpp executable. that's why i upload this PR

**Comment by NobodyXu** [comment]
I think you can create another crate cc-executable which uses cc to generate an archive first, then compile it to an executable.

The code in this PR breaks parallel compilation, whereas using cc to generate an archive first would support parallel compilation and easier to implement.

cc @thomcc  @ds1sqe I do think we can support generating object files instead of archive though, to support compiling to executable in another crate

**Pull request closed without merging**
