### PR TITLE
move documentation from README.md to lib.rs

### PR DESCRIPTION
**Pull request by Be-ing**
so it appears on https://docs.rs and inconsistencies aren't created between README.md and lib.rs

per discussion in https://github.com/rust-lang/cc-rs/issues/920

The old introductory text in lib.rs has been replaced with the text from README.md and the introductory paragraph revised. Otherwise no major changes to the text have been made.

I will follow this PR with more substantial edits to the text.

### CODE REVIEW

**Review by NobodyXu — APPROVED** [review]
Thanks, it LGTM but I would like feedback from others as well.

**Comment by NobodyXu** [comment]
cc @thomcc I would like your review on this PR

**Comment by NobodyXu** [comment]
I will merge this before next release to minimize the disruption.

**Comment by BlackHoleFox** [comment]
potentially both could be kept by using the [doc = include_str!](https://github.com/slint-ui/slint/blob/dd8fefd6a21cb319e28f956b415e36322fa1a810/tools/viewer/main.rs#L4) trick. I think `cc`'s MSRV is high enough for that now?

**Comment by Be-ing** [comment]
The trouble with `doc = include_str!("README.md")` is that https://github.com/rust-lang/cc-rs will show documentation for unreleased changes. I have been confused before by [another library](https://github.com/pdeljanov/Symphonia) doing that. Linking to https://docs.rs/cc doesn't have that issue; people will only see the documentation for published releases.

**Pull request merged**
