### PR TITLE
More env overrides

### PR DESCRIPTION
**Pull request by lu-zero**

### CODE REVIEW

**Comment by lu-zero** [comment]
The CI apparently had a network glitch.

**Comment by thomcc** [comment]
Interesting idea. I'll have to think about it.

**Comment by thomcc** [comment]
This is implemented in an opt-in way by https://github.com/rust-lang/cc-rs/pull/818. So I don't think we want this anymore.

**Comment by lu-zero** [comment]
I looked at the change, you do not want to have this feature opt-in since it would sort of defeat the purpose of having a standard way to pass optional flags to any crate that's using cc-rs.

**Pull request closed without merging**
