### PR TITLE
Bump msrv to 1.65

### PR DESCRIPTION
**Pull request by NobodyXu**
Required for #1137

### CODE REVIEW

**Comment by NobodyXu** [comment]
Unfortunately Debian stable is still on 1.63 https://packages.debian.org/search?keywords=rustc

**Comment by ChrisDenton** [comment]
What is the actual MSRV policy currently? It's used to be roughly stable - 2. But then this crate languished for awhile so the practical MSRV slipped further through inaction. While I don't think this needs the MSRV to be as aggressive as it used to be, I'm also not sure there's much reason to have Debian LTS as a baseline, It appears they already ship a cc-rs package: https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=librust-cc

**Comment by thomcc** [comment]
I'd be fine with something like stable-5. I know a lot of people have strong feelings about MSRV, but ancient MSRVs increase maintenance burden and we are low on those resources.

**Comment by thomcc** [comment]
More concretely, 1.65 is from 2022 so it seems fine to update to that now.

**Review by thomcc — APPROVED** [review]

**Comment by xtqqczze** [comment]
> More concretely, 1.65 is from 2022 so it seems fine to update to that now.

I think bumping the MSRV to 1.65 would be perfectly reasonable in 2026, see https://github.com/rust-lang/cc-rs/issues/1805.

**Pull request merged**
