### PR TITLE
Fix setting O_NONBLOCK in parallel::stderr::set_non_blocking

### LINKED ISSUE #945: 1.0.85 on FreeBSD breaks with assertion failure "stderr should have no flags set"
```
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-unknown-freebsd" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-fvisibility=hidden" "-ffunction-sections" "-fdata-sections" "-fmerge-all-constants" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-o" "/home/tyler/zofast/arrow-rs/target/debug/build/zstd-sys-275131524626fd8a/out/8957a4c8b028b07b-debug.o" "-c" "zstd/lib/common/debug.c"

  --- stderr
  thread 'main' panicked at /home/tyler/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cc-1.0.85/src/parallel/stderr.rs:17:9:
  assertion `left == right` failed: stderr should have no flags set
    left: 2
   right: 0
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I remember running into some issues with 1.0.84 which I know y'all ended up yanking, hit this on a fresh machine shortly after the 1.0.85 release  Sorry to be such a buzzkill :frowning: 

Will try to see what I can learn about the failure on a FreeBSD host. I wasn't able to reproduce it on x86_64-unknown-linux-gnu however

### PR DESCRIPTION
**Pull request by NobodyXu**
fix #945

### CODE REVIEW

**Comment by NobodyXu** [comment]
cc @rtyler  can you test this please?

**Comment by rtyler** [comment]
```
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "-m64" "--target=x86_64-unknown-freebsd" "-I" "zstd/lib/" "-I" "zstd/lib/common" "-I" "zstd/lib/legacy" "-fvisibility=hidden" "-ffunction-sections" "-fdata-sections" "-fmerge-all-constants" "-DZSTD_LIB_DEPRECATED=0" "-DXXH_PRIVATE_API=" "-DZSTDLIB_VISIBILITY=" "-DZDICTLIB_VISIBILITY=" "-DZSTDERRORLIB_VISIBILITY=" "-DZSTD_LEGACY_SUPPORT=1" "-o" "/home/tyler/zofast/zstd-rs/zstd-safe/zstd-sys/target/debug/build/zstd-sys-2363cb2b961a1de2/out/8957a4c8b028b07b-debug.o" "-c" "zstd/lib/common/debug.c"

  --- stderr
  thread 'main' panicked at /home/tyler/.cargo/git/checkouts/cc-rs-85fc25d64a0d5ded/0042c70/src/parallel/stderr.rs:17:9:
  assertion `left == right` failed: stderr should have no flags set
    left: 2
   right: 0
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
durian% nvim Cargo.toml
durian% cargo build
    Updating git repository `https://github.com/rust-lang/cc-rs`
   Compiling cc v1.0.85 (https://github.com/rust-lang/cc-rs?branch=NobodyXu-patch-1#aff20bf7)
   Compiling zstd-sys v2.0.9+zstd.1.5.5 (/home/tyler/zofast/zstd-rs/zstd-safe/zstd-sys)
    Finished dev [unoptimized + debuginfo] target(s) in 6.70s
durian%
```

Looks promising to me!

**Comment by NobodyXu** [comment]
@rtyler Thanks! I will get this merge and cut a release soon!

**Review by dpaoliello — APPROVED** [review]

**Comment by dpaoliello** [comment]
@Mark-Simulacrum gentle reminder to review this - it's blocking updates of cc-rs in the Rust compiler

**Review by Amanieu — APPROVED** [review]

**Comment by dpaoliello** [comment]
@NobodyXu can we please get a release with this change, or do you think it'd be OK to use 1.0.85 (I don't know what the implications of this issue would be)

**Comment by NobodyXu** [comment]
Yes I do want to cut a new release, but I'm worried about the regression in #948

**Pull request merged**
