### PR TITLE
split Tool and ToolFamily to a new tool module

### PR DESCRIPTION
**Pull request by Be-ing**

### CODE REVIEW

**Comment by NobodyXu** [comment]
I'm ok with this changes, but I'm afraid of creating merge conflicts that's a bit hard to fix in other PRs.

cc @thomcc what's your thought on this?

**Comment by Be-ing** [comment]
This is just moving code from one file to another. Merge conflicts should be pretty easy to resolve.

**Comment by NobodyXu** [comment]
> This is just moving code from one file to another. Merge conflicts should be pretty easy to resolve.

If someone modifies tool impl (e.g. #932 ) then it will have to rewrote it by moving changes into the new file.


Wirh rhat said, if #932 is the only PR that will have a merge conflict, then I'm willing to merge this and resolve the conflict myself.

**Comment by thomcc** [comment]
Sorry, I forgot to hit enter. I was going to say:

> I don't have strong feelings, and am willing to leave the decision up to you.

But with your comment that it's a single conflicting PR, I think we should go for it.

**Comment by NobodyXu** [comment]
There's also #907 (one-line change) and #851 (PR stale for a while).

So I will go ahead and merge it.

**Review by NobodyXu — APPROVED** [review]
Thanks, but you would need to resolve merge conflicts before I can merge it

**Comment by Be-ing** [comment]
Merge conflict fixed.

**Review by NobodyXu — APPROVED** [review]

**Pull request merged**
