### PR TITLE
rust.yml

### PR DESCRIPTION
**Pull request by Eianaftyio**
libraries state:open mentions:vmg

### CODE REVIEW

**Comment by Eianaftyio** [comment]
Eianaftyio:main

**Review by Eianaftyio — COMMENTED** [review]
libraries state:open mentions:vmg

**Comment by NobodyXu** [comment]
Sorry I can't understand the comment from you, and we already have a GHA CI configuration

**Review by Eianaftyio — COMMENTED** [review]
Ok whatever

**Pull request closed without merging**
