### PR TITLE
Optimize `Build::get_out_dir`: Return `Cow<'_, Path>`

### PR DESCRIPTION
**Pull request by NobodyXu**
to avoid heap allocation if possible.

### CODE REVIEW

**Comment by NobodyXu** [comment]
`Build::get_{target, host, opt_level, debug}` also returns `Cow<str>`, so it does make sense to also change `Build::get_out_dir` to return `Cow<'_, Path>`

**Comment by NobodyXu** [comment]
Closing this as I think there is a more aggressive optimization that can be done.

**Comment by NobodyXu** [comment]
> Closing this as I think there is a more aggressive optimization that can be done.

Reopened this since I realize that the more aggressive optimization I have in mind does not involve optimization for `Build::get_out_dir`.

**Review by thomcc — APPROVED** [review]
Seems fine.

**Pull request merged**
